### ISSUE TITLE
Подключение Vue, когда он не используется.

### ISSUE THREAD

**Issue by Sovgut** [0adrex0/FileSystem#2]
https://github.com/0adrex0/FileSystem/blob/3ae31813ffd3c4410c330ae4c5d788620a21a963/resources/js/app.js#L10

Вообще, мог бы уже и использовать Vue или подключить React, вместо тех что ты писал, я уже говорил что на каждом View писать отдельный скрипт, не самая хорошая затея, это лишь для быстрой реализации но это не совсем корректно.

Нарываешься на задачу с использованием Vue/React/Angular и Laravel 🤔

**Comment by 0adrex0** [comment]
Подключение Vue удалил
